CREATE TABLE Suppliers 
(
    Id INT IDENTITY(1,1),
    Name NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(200) NULL,
    Email NVARCHAR(100) NULL,
    Address NVARCHAR(255) NULL,

	PRIMARY KEY (Id)
)