--Truncate Table Passengers

INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Salman Irfani', DATEADD(Year, -22,GETDATE()), '737-081-6030', 'salmanirfani8@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Sameer', DATEADD(Year, -24,GETDATE()), '837-581-6090', 'sameer96@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Zahid', DATEADD(Year, -23,GETDATE()), '937-081-8090', 'Zahidahamad87@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Shabill', DATEADD(Year, -25,GETDATE()), '790-350-7622', 'shabill97@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Rohit Sharma', DATEADD(Year, -20,GETDATE()), '8860-081-6088', 'rohit1100@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Virat Kohli', DATEADD(Year, -35,GETDATE()), '930-000-0090', 'viratkohli001@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Deepika Bansal', DATEADD(Year, -28,GETDATE()), '737-221-6000', 'deepka999@gmail.com',  'F' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Charu Tiwari', DATEADD(Year, -29,GETDATE()), '737-081-5559', 'charu9088@gmail.com',  'F' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Rashi sharma', DATEADD(Year, -32,GETDATE()), '999-081-6000', 'rashisharma8700@gmail.com',  'F' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Parveen', DATEADD(Year, -19,GETDATE()), '933-081-8830', 'Parveen2200@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Majid Khan', DATEADD(Year, -65,GETDATE()), '937-663-7775', 'majidkhan5489@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Savitri Thakur', DATEADD(Year, -70,GETDATE()), '889-081-4030', 'savitri2220@gmail.com',  'F' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Rozi', DATEADD(Year, -45,GETDATE()), '937-001-6070', 'rozi333@gmail.com',  'F' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Zahid Ahmed', DATEADD(Year, -24,GETDATE()), '787-088-6060', 'zahidahmed0404@gmail.com',  'M' )


INSERT INTO Passengers ( Name, DOB, Mobile, Email, Gender )
	
	VALUES ('Nazish', DATEADD(Year, -26,GETDATE()), '987-088-9960', 'nazish1900@gmail.com',  'M' )











		