

INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Humsafar', 15036, 'Express', 'MuzaffarPur', 'Delhi')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Garib Rath', 12012, 'Express', 'MuzaffarPur', 'Delhi')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Mour Dhwaj', 12491, 'Special', 'MuzaffarPur', 'Kashmir')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Krambhoomi', 12545, 'Rajdhani', 'Patna', 'Mumbai')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Pawan', 12056, 'Express', 'Muzaffarpur', 'Mumbai')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Sawraj', 13046, 'Special', 'Mumbai', 'Mohali')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Mumbai', 12951, 'Rajdhani Exp', 'Mumbai', 'Delhi')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Sealda', 20822, 'Express', 'Kolkata', 'Mumbai')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Assam', 20936, 'Special', 'Assam', 'Goa')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Janta', 25036, 'Express', 'Patna', 'Mumbai')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Himsagar', 16317, 'Rajdhani Exp', 'Tripura', 'Kashmir')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Kerala', 12484, 'Express', 'Punjab', 'Kerala')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Nicobar', 16031, 'Speical', 'Delhi', 'Nicobar')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Jnaneswari', 12102, 'Express', 'Tatanagar', 'Mumbai')


INSERT INTO Trains (Name, TrainNo, TrainTypes, SourceCity, DestinationCity)

			VALUES('Swarna Jayanti', 12818, 'Express', 'Kanpur', 'Ranchi')






