--Truncate Table TrainStoppages

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (1, 'Barauni', DateAdd(Hour, 24, GetDate()))


Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (1, 'Samastipur', DateAdd(Hour, 20, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (1, 'Chhapra', DateAdd(Hour, 17, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (1, 'GorakPur', DateAdd(Hour, 10, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (1, 'Delhi', DateAdd(Hour, -1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (2, 'Jaynagar', DateAdd(Hour, 26, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (2, 'Sivan', DateAdd(Hour, 15, GetDate()))


Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (2, 'Kanpur', DateAdd(Hour, 7, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (2, 'Anand Vihar', DateAdd(Hour, -2, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (3, 'Motihari', DateAdd(Hour, 48, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (3, 'Faizabad', DateAdd(Hour, 40, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (3, 'Agra', DateAdd(Hour, 30, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (3, 'Ludhiana', DateAdd(Hour, 24, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (3, 'Pathankot', DateAdd(Hour, 10, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (3, 'Kashmir', DateAdd(Hour, 1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (4, 'DanaPur', DateAdd(Hour, 30, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (4, 'MirzaPur', DateAdd(Hour, 20, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (4, 'Nashik', DateAdd(Hour, 5, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (4, 'Mumbai', DateAdd(Hour, -2, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (5, 'SamastiPur', DateAdd(Hour, 30, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (5, 'Ambala', DateAdd(Hour, 15, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (5, 'Pune', DateAdd(Hour, -1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (6, 'Mumbai', DateAdd(Hour, 28, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (6, 'Kanpur', DateAdd(Hour, 16, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (6, 'Amritsar', DateAdd(Hour, 4, GetDate()))


Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (6, 'Mohali', DateAdd(Hour, -2, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (7, 'Navi Mumbai', DateAdd(Hour, 20, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (7, 'Surat', DateAdd(Hour, 12, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (7, 'Mathura', DateAdd(Hour, 4, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (7, 'New Delhi', DateAdd(Hour, -1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (8, 'Howra', DateAdd(Hour, 35, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (8, 'Jabalpur', DateAdd(Hour, 15, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (8, 'Mumbai', DateAdd(Hour, -1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (9, 'Nilbagan', DateAdd(Hour, 50, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (9, 'Guwahati', DateAdd(Hour, 30, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (9, 'MuzaffarPur', DateAdd(Hour, 20, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (9, 'NagPur', DateAdd(Hour, 10, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (9, 'Goa', DateAdd(Hour, -1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (10, 'Patna', DateAdd(Hour, 30, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (10, 'Lucknow', DateAdd(Hour, 20, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (10, 'Nashik', DateAdd(Hour, 5, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (10, 'Navi Mumbai', DateAdd(Hour, -1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (11, 'Tripura', DateAdd(Hour, 52, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (11, 'Assam', DateAdd(Hour, 40, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (11, 'Patna', DateAdd(Hour, 35, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (11, 'New Delhi', DateAdd(Hour, 20, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (11, 'Jalandhar', DateAdd(Hour, 8, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (11, 'kashmir', DateAdd(Hour, -2, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (12, 'Howra', DateAdd(Hour, 35, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (12, 'Tatanagar', DateAdd(Hour, 24, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (12, 'Jabalpur', DateAdd(Hour, 15, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (12, 'Mumbai', DateAdd(Hour, -1, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (13, 'Lucknow', DateAdd(Hour, 20, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (13, 'PrayagRaj', DateAdd(Hour, 15, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (13, 'Gaya', DateAdd(Hour, 9, GetDate()))

Insert Into TrainStoppages ( TrainId, Station, ReachTime)
	Values (13, 'Ranchi', DateAdd(Hour, -1, GetDate()))











