CREATE TABLE Patients 
(
    Id INT IDENTITY(1,1),
    FirstName NVARCHAR(200) NOT NULL,
    LastName NVARCHAR(200) NOT NULL,
    DOB DATETIME NOT NULL,
    Gender NVARCHAR(100) NOT NULL,
	BloodGroup NVARCHAR(100) NOT NULL,
    ContactNumber NVARCHAR(200) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    AddressId INT NOT NULL,
	PRIMARY KEY (Id)
)

ALTER TABLE Patients
ADD FOREIGN KEY (AddressId) REFERENCES Addresses(Id)