CREATE TABLE JobProvider 
(
    Id INT IDENTITY(1,1),
    CompanyName NVARCHAR(100) NOT NULL,
    Industry NVARCHAR(200) NOT NULL,
    Email NVARCHAR(200) NOT NULL UNIQUE,
	Password NVARCHAR(200) NOT NULL,
    Phone NVARCHAR(200) NOT NULL,
    Website NVARCHAR(200) NOT NULL,
    AboutUs NVARCHAR(300) NOT NULL,
    RegistrationDate DATETIME DEFAULT GETDATE(),

	PRIMARY KEY(Id)
)